//
// Created by Olivier Marin on 29/03/2016.
//

#ifndef CRYPTOPROTOCOLCLIENT_AUTH_H
#define CRYPTOPROTOCOLCLIENT_AUTH_H


int checkUser(char* user, char* pass);
int searchInDB(char *str);

#define SALTME "CAKUHDFBAOZEFHUBLAEHFBDLAUHEFBALZHFEBALUEFVKAUHFDBAZEFHBA"

#endif //CRYPTOPROTOCOLCLIENT_AUTH_H
